// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class DatetimeType
    {
        public const string Codename = "datetime";
        public const string DatetimeCodename = "datetime";

        public IDateTimeContent Datetime { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}