// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class Linked
    {
        public const string Codename = "linked";
        public const string UntitledLinkedItemsCodename = "untitled_linked_items";

        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> UntitledLinkedItems { get; set; }
    }
}