// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class Tobechangedafter
    {
        public const string Codename = "tobechangedafter";
        public const string UntitledTextCodename = "untitled_text";
        public const string UntitledUrlSlugCodename = "untitled_url_slug";

        public IContentItemSystemAttributes System { get; set; }
        public string UntitledText { get; set; }
        public string UntitledUrlSlug { get; set; }
    }
}