// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class UntitledContentType
    {
        public const string Codename = "untitled_content_type";
        public const string MultiplechoiceCodename = "multiplechoice";
        public const string RteCodename = "rte";
        public const string UntitledLinkedItemsCodename = "untitled_linked_items";
        public const string UntitledMultipleChoiceCodename = "untitled_multiple_choice";
        public const string UntitledMultipleChoice63e2087Codename = "untitled_multiple_choice_63e2087";
        public const string UntitledText88f0d6eCodename = "untitled_text_88f0d6e";
        public const string UntitledUrlSlugCodename = "untitled_url_slug";

        public IEnumerable<IMultipleChoiceOption> Multiplechoice { get; set; }
        public IRichTextContent Rte { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> UntitledLinkedItems { get; set; }
        public IEnumerable<IMultipleChoiceOption> UntitledMultipleChoice { get; set; }
        public IEnumerable<IMultipleChoiceOption> UntitledMultipleChoice63e2087 { get; set; }
        public string UntitledText88f0d6e { get; set; }
        public string UntitledUrlSlug { get; set; }
    }
}