// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class Withgroups
    {
        public const string Codename = "withgroups";
        public const string Group1text1Codename = "group1text1";
        public const string Group2text1Codename = "group2text1";

        public string Group1text1 { get; set; }
        public string Group2text1 { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}